service:
  name: tracking-detector

application:
  path: ${base.url}

base:
  url: http://localhost:${server.port}

server:
  port: 3000

spring:
  data:
    mongodb:
      host: ${MONGO_DB_HOST}
      port: ${MONGO_DB_PORT}
      database: ${MONGO_DB_DATABASE}
  application:
    name: ${service.name}

rpc:
  host: ${RPC_HOST}
  port: ${RPC_PORT}
  method: ${RPC_METHOD}

minio:
  url: ${MINIO_URL}
  port: ${MINIO_PORT}
  accessKey: ${MINIO_ACCESS_KEY}
  privateKey: ${MINIO_PRIVATE_KEY}

buckets:
  trainingDataBucket: ${TRAINING_DATA_BUCKET}
  modelBucket: ${MODEL_BUCKET}
  mongoDbBackupBucket: ${MONGO_DB_BACKUP_BUCKET}
